### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by elge70** [romac/react-if#177]
With React 18 types, \<If\> has an issue. I get the following error 
TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.

**Comment by favna** [comment]
I haven't looked into it yet but was this with or without `@types/react` v18? I saw that version was released within the last week as Renovate bumped some of my other repos last night.

**Comment by hcharley** [comment]
Here is a good explainer on the breaking change @elge70 is running into:

https://solverfox.dev/writing/no-implicit-children/

**Comment by favna** [comment]
I can easily repro the issue by updating the dependency, though I cannot quite tell what the actual fix is from the article. At the time of writing I am rewriting the unit tests to react-testing-library since enzyme _**still**_ doesn't support React 17, let alone 18. If there are any replies here at a later time with a suggestion for the fix that would be very much appreciated. Otherwise I'll get around it eventually.

**Comment by favna** [comment]
I fixed the typings and source code, but I am still updating tests

**Comment by favna** [comment]
A fix has been published to NPM with version 4.1.2
