### ISSUE TITLE
bug: type inference

### ISSUE THREAD

**Issue by Xstoudi** [romac/react-if#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

For example, if we have an `article` const being `Article | null`:
```tsx
<If condition={article === null}>
  <Then>
    <NoArticle />
  </Then>

  <Else>
    {article.title} <---- TypeScript error because article is possibly null
  </Else>
</If>
```

### Steps To Reproduce

Try to infer type.

### Expected behavior

`article` type should be infered as `Article` as we already checked the `null` case.

**Comment by favna** [comment]
As far as I know this library cannot offer type inferences because the library doesn't know what kind of condition you are going to write. For example, it cannot simply do `Exclude<T, null>` because for all the library knows the user wrote `!== undefined`. 

From my own experience using it, you're better off using regular if/else statements if you need type inference.

**Comment by favna** [comment]
Closing this because as stated above, it's simply not possible. If this ever changes we can revisit it later.
